# Generated by Django 4.2.5 on 2023-09-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_serving_time_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient/cover/', verbose_name='cover'),
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
