name: CD-Liara
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@4
          liara deploy --app="healitia-backend" --api-token="$LIARA_TOKEN" --detach --port=8000
          sleep 60
          liara shell --app="healitia-backend" --command "python manage.py migrate" --api-token="$LIARA_TOKEN"